/**
 * Offline practice questions
 * Used when the backend can't supply questions for the selected exam section
 */

import type { ExamId, Pace, SectionId } from './exam'
import type { SATQuestion } from './api/questions'

type BankQuestion = Omit<SATQuestion, 'exam' | 'section' | 'source' | 'sourceName'>

const QC_OPTIONS = [
  'Quantity A is greater.',
  'Quantity B is greater.',
  'The two quantities are equal.',
  'The relationship cannot be determined from the information given.',
]

const SAT_TEXT_PROMPT = 'Which choice completes the text with the most logical and precise word or phrase?'
const SAT_CONVENTIONS_PROMPT = 'Which choice completes the text so that it conforms to the conventions of Standard English?'

const satQuant: BankQuestion[] = [
  {
    id: 9001,
    question: 'If 3x − 7 = 11, what is the value of 6x?',
    options: ['18', '30', '36', '42'],
    correctAnswer: 2,
    topic: 'Algebra',
    difficulty: 'easy',
    explanation: 'Adding 7 to both sides gives 3x = 18. Doubling both sides gives 6x = 36.',
  },
  {
    id: 9002,
    question: 'A store sells notebooks for $4 each. A 15% discount is applied to an order of 10 notebooks. What is the total cost of the order?',
    options: ['$25', '$34', '$36', '$46'],
    correctAnswer: 1,
    topic: 'Problem-Solving and Data Analysis',
    difficulty: 'easy',
    explanation: 'Ten notebooks cost $40 before the discount. 15% of $40 is $6, so the total is $40 − $6 = $34.',
  },
  {
    id: 9003,
    question: 'A rectangle has a length of 12 and a width of 5. What is the length of its diagonal?',
    options: ['13', '17', '30', '60'],
    correctAnswer: 0,
    topic: 'Geometry and Trigonometry',
    difficulty: 'easy',
    explanation: 'The diagonal is the hypotenuse of a right triangle with legs 5 and 12: √(25 + 144) = √169 = 13.',
  },
  {
    id: 9004,
    question: 'Which expression is equivalent to (x + 3)² − (x − 3)²?',
    options: ['0', '18', '12x', '2x² + 18'],
    correctAnswer: 2,
    topic: 'Advanced Math',
    difficulty: 'medium',
    explanation: '(x² + 6x + 9) − (x² − 6x + 9) = 12x.',
  },
  {
    id: 9005,
    question: '2x + y = 10\nx − y = 2\n\nThe solution to the given system of equations is (x, y). What is the value of y?',
    options: ['2', '4', '6', '8'],
    correctAnswer: 0,
    topic: 'Algebra',
    difficulty: 'medium',
    explanation: 'Adding the equations gives 3x = 12, so x = 4. Substituting into x − y = 2 gives y = 2.',
  },
  {
    id: 9006,
    question: 'The mean of five numbers is 14. Four of the numbers are 10, 12, 15, and 18. What is the fifth number?',
    options: ['13', '14', '15', '16'],
    correctAnswer: 2,
    topic: 'Problem-Solving and Data Analysis',
    difficulty: 'medium',
    explanation: 'The five numbers sum to 5 × 14 = 70. The four known numbers sum to 55, so the fifth is 70 − 55 = 15.',
  },
  {
    id: 9007,
    question: 'The function f is defined by f(x) = x² − 6x + 13. What is the minimum value of f?',
    options: ['3', '4', '9', '13'],
    correctAnswer: 1,
    topic: 'Advanced Math',
    difficulty: 'hard',
    explanation: 'Completing the square gives f(x) = (x − 3)² + 4, which has a minimum value of 4 when x = 3.',
  },
  {
    id: 9008,
    question: 'For what value of the constant k does the equation 4x + k = 2(2x + 5) have infinitely many solutions?',
    options: ['0', '5', '10', '20'],
    correctAnswer: 2,
    topic: 'Algebra',
    difficulty: 'hard',
    explanation: 'The right side is 4x + 10. The equation is true for every x only if the constants match, so k = 10.',
  },
  {
    id: 9009,
    question: 'In a right triangle, θ is an acute angle and sin θ = 3/5. What is the value of tan θ?',
    options: ['3/4', '4/5', '4/3', '5/3'],
    correctAnswer: 0,
    topic: 'Geometry and Trigonometry',
    difficulty: 'hard',
    explanation: 'With opposite side 3 and hypotenuse 5, the adjacent side is 4. So tan θ = opposite/adjacent = 3/4.',
  },
]

const satVerbal: BankQuestion[] = [
  {
    id: 9101,
    passage: "Although the committee's early drafts were criticized as vague, its final report was remarkably ______, laying out each recommendation in clear and specific terms.",
    question: SAT_TEXT_PROMPT,
    options: ['precise', 'tentative', 'lengthy', 'controversial'],
    correctAnswer: 0,
    topic: 'Craft and Structure',
    difficulty: 'easy',
    explanation: '"Precise" contrasts with "vague" and matches "clear and specific terms."',
  },
  {
    id: 9102,
    passage: 'The collection of rare maps, which includes several hand-drawn charts from the 1600s, ______ on display at the city library through March.',
    question: SAT_CONVENTIONS_PROMPT,
    options: ['are', 'is', 'were', 'have been'],
    correctAnswer: 1,
    topic: 'Standard English Conventions',
    difficulty: 'easy',
    explanation: 'The subject is the singular noun "collection," so it takes the singular verb "is."',
  },
  {
    id: 9103,
    passage: 'Honeybees communicate the location of food through a pattern of movements known as the waggle dance. ______ a bee that finds a rich patch of flowers can direct its hive mates to the same spot.',
    question: 'Which choice completes the text with the most logical transition?',
    options: ['However,', 'By contrast,', 'In this way,', 'Nevertheless,'],
    correctAnswer: 2,
    topic: 'Expression of Ideas',
    difficulty: 'easy',
    explanation: 'The second sentence describes what the dance accomplishes, so "In this way" fits. The other choices signal a contrast that is not there.',
  },
  {
    id: 9104,
    passage: 'Urban ecologists once assumed that cities were poor habitats for wildlife. Recent surveys, however, have documented coyotes, peregrine falcons, and even rare orchids thriving in dense metropolitan areas. Some species appear to benefit from city life: falcons nest on skyscraper ledges that resemble cliffs, and they hunt the pigeons that cities supply in abundance.',
    question: 'Which choice best states the main idea of the text?',
    options: [
      'Peregrine falcons prefer skyscrapers to natural cliffs.',
      'Urban ecologists have stopped studying rural habitats.',
      'Cities can be suitable, and even advantageous, habitats for some wildlife.',
      'Most species cannot survive in metropolitan areas.',
    ],
    correctAnswer: 2,
    topic: 'Information and Ideas',
    difficulty: 'medium',
    explanation: 'The text corrects the old assumption by showing species that thrive in, and even benefit from, cities.',
  },
  {
    id: 9105,
    passage: 'The biologist Lynn Margulis proposed a bold ______ that mitochondria, the structures that power complex cells, were once free-living bacteria.',
    question: SAT_CONVENTIONS_PROMPT,
    options: ['idea,', 'idea:', 'idea;', 'idea'],
    correctAnswer: 3,
    topic: 'Standard English Conventions',
    difficulty: 'medium',
    explanation: 'The clause beginning with "that" is essential to "idea," so no punctuation should separate them.',
  },
  {
    id: 9106,
    passage: 'In a study of sleep and memory, participants who napped for 60 minutes after learning a list of words recalled significantly more words than participants who stayed awake. The researchers concluded that deep sleep, specifically, strengthens new memories.',
    question: "Which finding, if true, would most directly support the researchers' conclusion?",
    options: [
      'Participants who napped reported feeling more rested than those who stayed awake.',
      'Participants whose naps contained more deep sleep recalled more words than those whose naps contained less.',
      'Participants who stayed awake spent the hour reading.',
      'Most participants fell asleep within ten minutes.',
    ],
    correctAnswer: 1,
    topic: 'Information and Ideas',
    difficulty: 'medium',
    explanation: 'Only this finding ties the amount of deep sleep, rather than napping in general, to better recall.',
  },
  {
    id: 9107,
    passage: "The novelist's prose is often described as austere, yet her latest work is surprisingly ______: sentences sprawl across pages, crowded with ornate imagery and elaborate digressions.",
    question: SAT_TEXT_PROMPT,
    options: ['restrained', 'obscure', 'conventional', 'lavish'],
    correctAnswer: 3,
    topic: 'Craft and Structure',
    difficulty: 'hard',
    explanation: '"Yet" signals a contrast with "austere," and sprawling, ornate sentences are "lavish."',
  },
  {
    id: 9108,
    passage: "Archaeologists excavating a coastal settlement found fishhooks and net weights in its oldest layers but almost none in the layers above, which instead contained grinding stones and storage pits for grain. The settlement was continuously occupied throughout this period, and there is no evidence that the nearby coastline shifted. This suggests that the settlement's inhabitants ______",
    question: 'Which choice most logically completes the text?',
    options: [
      'gradually shifted from relying on fishing to relying on agriculture.',
      'abandoned the site when fish became scarce.',
      'traded grain for fish with neighboring communities.',
      'moved inland as sea levels rose.',
    ],
    correctAnswer: 0,
    topic: 'Information and Ideas',
    difficulty: 'hard',
    explanation: 'Fishing tools give way to grain-processing tools while the site stays occupied and the coast stays put, pointing to a change in how people got food.',
  },
  {
    id: 9109,
    passage: 'Having studied the migration of monarch butterflies for three decades, ______',
    question: SAT_CONVENTIONS_PROMPT,
    options: [
      'the data collected by Dr. Ruiz reveal a steady decline in their numbers.',
      "a steady decline in their numbers has been revealed by Dr. Ruiz's data.",
      'Dr. Ruiz has collected data that reveal a steady decline in their numbers.',
      "there is a steady decline in their numbers, according to Dr. Ruiz's data.",
    ],
    correctAnswer: 2,
    topic: 'Standard English Conventions',
    difficulty: 'hard',
    explanation: 'The opening modifier describes the person who studied the butterflies, so "Dr. Ruiz" must come right after the comma.',
  },
]

const greQuant: BankQuestion[] = [
  {
    id: 9201,
    question: 'If 5 − 2x > 11, which of the following must be true?',
    options: ['x > 3', 'x < 3', 'x > −3', 'x < −3', 'x = −3'],
    correctAnswer: 3,
    topic: 'Algebra',
    difficulty: 'easy',
    explanation: 'Subtracting 5 gives −2x > 6. Dividing by −2 reverses the inequality: x < −3.',
  },
  {
    id: 9202,
    question: 'Quantity A: 25% of 80\nQuantity B: 80% of 25',
    options: QC_OPTIONS,
    correctAnswer: 2,
    topic: 'Arithmetic',
    difficulty: 'easy',
    explanation: 'Both quantities equal 20.',
  },
  {
    id: 9203,
    question: 'The average (arithmetic mean) of 4 numbers is 15. When one of the numbers is removed, the average of the remaining 3 numbers is 12. What number was removed?',
    options: ['18', '21', '24', '27', '30'],
    correctAnswer: 2,
    topic: 'Data Analysis',
    difficulty: 'easy',
    explanation: 'The four numbers sum to 60 and the remaining three sum to 36, so the removed number is 24.',
  },
  {
    id: 9204,
    question: 'A jar contains 4 red marbles and 6 blue marbles. If two marbles are drawn at random without replacement, what is the probability that both are red?',
    options: ['1/15', '2/15', '4/25', '1/5', '2/5'],
    correctAnswer: 1,
    topic: 'Data Analysis',
    difficulty: 'medium',
    explanation: '(4/10) × (3/9) = 12/90 = 2/15.',
  },
  {
    id: 9205,
    question: 'x and y are positive integers, and xy = 36.\n\nQuantity A: x + y\nQuantity B: 12',
    options: QC_OPTIONS,
    correctAnswer: 3,
    topic: 'Arithmetic',
    difficulty: 'medium',
    explanation: 'If x = y = 6, the sum is 12 and the quantities are equal. If x = 4 and y = 9, the sum is 13 and Quantity A is greater.',
  },
  {
    id: 9206,
    question: 'A car travels the first 60 miles of a trip at 30 miles per hour and the next 60 miles at 60 miles per hour. What is its average speed, in miles per hour, for the entire trip?',
    options: ['40', '42', '45', '48', '50'],
    correctAnswer: 0,
    topic: 'Arithmetic',
    difficulty: 'medium',
    explanation: 'The trip takes 2 hours + 1 hour = 3 hours for 120 miles, so the average speed is 40 miles per hour.',
  },
  {
    id: 9207,
    question: 'How many positive integers less than 100 are divisible by 3 but not by 5?',
    options: ['20', '24', '27', '30', '33'],
    correctAnswer: 2,
    topic: 'Arithmetic',
    difficulty: 'hard',
    explanation: 'There are 33 multiples of 3 below 100. Six of them (15, 30, 45, 60, 75, 90) are also multiples of 5, leaving 27.',
  },
  {
    id: 9208,
    question: 'If x² − y² = 48 and x − y = 4, what is the value of x?',
    options: ['4', '6', '8', '10', '12'],
    correctAnswer: 2,
    topic: 'Algebra',
    difficulty: 'hard',
    explanation: 'x² − y² = (x − y)(x + y), so x + y = 12. Adding x − y = 4 gives 2x = 16, so x = 8.',
  },
  {
    id: 9209,
    question: 'A circle has a circumference of 10π.\n\nQuantity A: The area of the circle\nQuantity B: 75',
    options: QC_OPTIONS,
    correctAnswer: 0,
    topic: 'Geometry',
    difficulty: 'hard',
    explanation: 'The radius is 5, so the area is 25π, which is about 78.5 and greater than 75.',
  },
]

const greVerbal: BankQuestion[] = [
  {
    id: 9301,
    question: "Despite the professor's reputation for being ______, her lectures were surprisingly lively and engaging.",
    options: ['dull', 'brilliant', 'generous', 'punctual', 'famous'],
    correctAnswer: 0,
    topic: 'Text Completion',
    difficulty: 'easy',
    explanation: '"Despite" and "surprisingly" call for the opposite of "lively and engaging."',
  },
  {
    id: 9302,
    question: 'The treaty was intended to be ______, but within a year both nations had returned to open hostility.',
    options: ['provisional', 'lasting', 'secret', 'punitive', 'ambiguous'],
    correctAnswer: 1,
    topic: 'Text Completion',
    difficulty: 'easy',
    explanation: '"But" contrasts the intention with the quick return to hostility, so the treaty was meant to be lasting.',
  },
  {
    id: 9303,
    question: "Because the witness's account was ______ by security footage, the jury found it easy to believe.",
    options: ['obscured', 'contradicted', 'anticipated', 'corroborated', 'complicated'],
    correctAnswer: 3,
    topic: 'Text Completion',
    difficulty: 'easy',
    explanation: 'Footage that makes an account easy to believe confirms, or corroborates, it.',
  },
  {
    id: 9304,
    question: "Far from being ______, the committee's decision was reached only after months of careful deliberation.",
    options: ['hasty', 'unanimous', 'popular', 'judicious', 'final'],
    correctAnswer: 0,
    topic: 'Text Completion',
    difficulty: 'medium',
    explanation: '"Far from" sets up the opposite of months of careful deliberation: a hasty decision.',
  },
  {
    id: 9305,
    passage: "Many historians have attributed the decline of the medieval guilds to the rise of factory production. Yet guild membership in several European cities had already fallen sharply decades before the first factories appeared, as merchants began contracting work to rural households beyond the guilds' control.",
    question: 'The passage suggests that the decline of the guilds',
    options: [
      'was caused primarily by the growth of cities',
      'was slower than most historians believe',
      'began before factory production could have caused it',
      'resulted from conflicts among guild members',
      'had little effect on rural households',
    ],
    correctAnswer: 2,
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    explanation: 'Membership fell "decades before the first factories appeared," so factories cannot explain the start of the decline.',
  },
  {
    id: 9306,
    question: "The critic's review was so ______ that even the film's director admitted it had identified real flaws rather than merely expressing dislike.",
    options: ['vitriolic', 'perceptive', 'perfunctory', 'effusive', 'cryptic'],
    correctAnswer: 1,
    topic: 'Text Completion',
    difficulty: 'medium',
    explanation: 'A review that identifies real flaws shows insight, which is what "perceptive" means.',
  },
  {
    id: 9307,
    question: 'Her argument, though ______ at first glance, collapses under scrutiny: its premises are sound individually but cannot all be true together.',
    options: ['tedious', 'incoherent', 'modest', 'derivative', 'compelling'],
    correctAnswer: 4,
    topic: 'Text Completion',
    difficulty: 'hard',
    explanation: '"Though" contrasts the first impression with the collapse under scrutiny, so the argument at first seems compelling.',
  },
  {
    id: 9308,
    question: "The senator's ______ during the hearing (he answered every pointed question with a rambling anecdote) frustrated those hoping for a direct statement of his position.",
    options: ['candor', 'concision', 'circumlocution', 'belligerence', 'erudition'],
    correctAnswer: 2,
    topic: 'Text Completion',
    difficulty: 'hard',
    explanation: 'Circumlocution is roundabout, evasive speech, which matches rambling answers that avoid a direct statement.',
  },
  {
    id: 9309,
    passage: "A researcher argues that a region's sudden drop in bird populations was caused by a new pesticide, noting that the decline began the same year the pesticide was introduced.",
    question: "Which of the following, if true, most seriously weakens the researcher's argument?",
    options: [
      'The pesticide is more expensive than the one it replaced.',
      'Some farmers in the region used the pesticide more heavily than others.',
      'The pesticide is known to kill insects that birds eat.',
      'Bird populations declined just as sharply that year in nearby regions where the pesticide was never used.',
      'Bird populations in the region had been stable for the previous decade.',
    ],
    correctAnswer: 3,
    topic: 'Reading Comprehension',
    difficulty: 'hard',
    explanation: 'An equal decline where the pesticide was never used points to some other cause.',
  },
]

const BANK: Record<ExamId, Record<SectionId, BankQuestion[]>> = {
  sat: { quant: satQuant, verbal: satVerbal },
  gre: { quant: greQuant, verbal: greVerbal },
}

// Quick games skip the hard questions; deep games skip the easy ones
const PACE_EXCLUDES: Record<Pace, SATQuestion['difficulty']> = { quick: 'hard', deep: 'easy' }

export function getBankQuestions(exam: ExamId, section: SectionId, pace?: Pace): SATQuestion[] {
  const questions = BANK[exam][section].filter((q) => !pace || q.difficulty !== PACE_EXCLUDES[pace])
  return questions.map((q) => ({
    ...q,
    // Games that only show `question` still need the passage
    question: q.passage ? `${q.passage}\n\n${q.question}` : q.question,
    stem: q.question,
    exam,
    section,
    source: 'practice',
    sourceName: 'Built-in practice set',
  }))
}
